[tool.poetry]
name = "desafio_data"
version = "0.1.0"
description = ""
authors = ["Tu_Nombre <tu_mail@tu_mail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
